### ISSUE TITLE
Symlink job fails on check

### ISSUE THREAD

**Issue by jondequinor** [equinor/komodo#92]
```+ komodo-create-symlinks symlink_configuration/symlink_config.json
+ komodo-check-symlinks symlink_configuration/symlink_config.json
Traceback (most recent call last):
  File "/var/jenkins/jenkins-komodo/workspace/komodo-symlink/.venv/bin/komodo-check-symlinks", line 11, in <module>
    load_entry_point('Komodo==1.0', 'console_scripts', 'komodo-check-symlinks')()
  File "/var/jenkins/jenkins-komodo/workspace/komodo-symlink/.venv/lib/python3.6/site-packages/komodo/symlink/sanity_check.py", line 108, in sanity_main
    assert_root_nodes(input_dict)
  File "/var/jenkins/jenkins-komodo/workspace/komodo-symlink/.venv/lib/python3.6/site-packages/komodo/symlink/sanity_check.py", line 85, in assert_root_nodes
    "The roots in the link-tree is not matching the roots defined in link_roots in dict"
AssertionError: The roots in the link-tree is not matching the roots defined in link_roots in dict```

**Comment by oysteoh** [comment]
resolved in  https://github.com/equinor/komodo-releases/pull/465
